//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKU_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Designcs {
            get {
                return ((string)(this["Designcs"]));
            }
            set {
                this["Designcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BestbuyTable1 {
            get {
                return ((global::System.Data.DataTable)(this["BestbuyTable1"]));
            }
            set {
                this["BestbuyTable1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BestbuyTable2 {
            get {
                return ((global::System.Data.DataTable)(this["BestbuyTable2"]));
            }
            set {
                this["BestbuyTable2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable AmazonCaTable {
            get {
                return ((global::System.Data.DataTable)(this["AmazonCaTable"]));
            }
            set {
                this["AmazonCaTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable AmazonComTable {
            get {
                return ((global::System.Data.DataTable)(this["AmazonComTable"]));
            }
            set {
                this["AmazonComTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable StaplesTable {
            get {
                return ((global::System.Data.DataTable)(this["StaplesTable"]));
            }
            set {
                this["StaplesTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable WalmartItemTable {
            get {
                return ((global::System.Data.DataTable)(this["WalmartItemTable"]));
            }
            set {
                this["WalmartItemTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ActivePriceTable {
            get {
                return ((global::System.Data.DataTable)(this["ActivePriceTable"]));
            }
            set {
                this["ActivePriceTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable UpcTable {
            get {
                return ((global::System.Data.DataTable)(this["UpcTable"]));
            }
            set {
                this["UpcTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASCMcs {
            get {
                return ((string)(this["ASCMcs"]));
            }
            set {
                this["ASCMcs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable MagentoTable {
            get {
                return ((global::System.Data.DataTable)(this["MagentoTable"]));
            }
            set {
                this["MagentoTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable GiantTigerTable {
            get {
                return ((global::System.Data.DataTable)(this["GiantTigerTable"]));
            }
            set {
                this["GiantTigerTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable StockQuantityTable {
            get {
                return ((global::System.Data.DataTable)(this["StockQuantityTable"]));
            }
            set {
                this["StockQuantityTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable WalmartPriceTable {
            get {
                return ((global::System.Data.DataTable)(this["WalmartPriceTable"]));
            }
            set {
                this["WalmartPriceTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable UducatTable {
            get {
                return ((global::System.Data.DataTable)(this["UducatTable"]));
            }
            set {
                this["UducatTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPcodedBlankTable {
            get {
                return ((global::System.Data.DataTable)(this["BPcodedBlankTable"]));
            }
            set {
                this["BPcodedBlankTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPcodedImprintTable {
            get {
                return ((global::System.Data.DataTable)(this["BPcodedImprintTable"]));
            }
            set {
                this["BPcodedImprintTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPrushCodedBlankTable {
            get {
                return ((global::System.Data.DataTable)(this["BPrushCodedBlankTable"]));
            }
            set {
                this["BPrushCodedBlankTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPrushCodedImprintTable {
            get {
                return ((global::System.Data.DataTable)(this["BPrushCodedImprintTable"]));
            }
            set {
                this["BPrushCodedImprintTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPnetBlankTable {
            get {
                return ((global::System.Data.DataTable)(this["BPnetBlankTable"]));
            }
            set {
                this["BPnetBlankTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPnetImprintTable {
            get {
                return ((global::System.Data.DataTable)(this["BPnetImprintTable"]));
            }
            set {
                this["BPnetImprintTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPrushNetBlankTable {
            get {
                return ((global::System.Data.DataTable)(this["BPrushNetBlankTable"]));
            }
            set {
                this["BPrushNetBlankTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPrushNetImprintTable {
            get {
                return ((global::System.Data.DataTable)(this["BPrushNetImprintTable"]));
            }
            set {
                this["BPrushNetImprintTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ShopCaBagTable {
            get {
                return ((global::System.Data.DataTable)(this["ShopCaBagTable"]));
            }
            set {
                this["ShopCaBagTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ShopCaBaseDataTable {
            get {
                return ((global::System.Data.DataTable)(this["ShopCaBaseDataTable"]));
            }
            set {
                this["ShopCaBaseDataTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ShopCaPriceTable {
            get {
                return ((global::System.Data.DataTable)(this["ShopCaPriceTable"]));
            }
            set {
                this["ShopCaPriceTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ShopCaInventoryTable {
            get {
                return ((global::System.Data.DataTable)(this["ShopCaInventoryTable"]));
            }
            set {
                this["ShopCaInventoryTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable DistributorCentralTable {
            get {
                return ((global::System.Data.DataTable)(this["DistributorCentralTable"]));
            }
            set {
                this["DistributorCentralTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Remember {
            get {
                return ((bool)(this["Remember"]));
            }
            set {
                this["Remember"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ChannelListingTable {
            get {
                return ((global::System.Data.DataTable)(this["ChannelListingTable"]));
            }
            set {
                this["ChannelListingTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ChannelHasListingTable {
            get {
                return ((global::System.Data.DataTable)(this["ChannelHasListingTable"]));
            }
            set {
                this["ChannelHasListingTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable ChannelNewListingTable {
            get {
                return ((global::System.Data.DataTable)(this["ChannelNewListingTable"]));
            }
            set {
                this["ChannelNewListingTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable SageTable {
            get {
                return ((global::System.Data.DataTable)(this["SageTable"]));
            }
            set {
                this["SageTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable AsiTable {
            get {
                return ((global::System.Data.DataTable)(this["AsiTable"]));
            }
            set {
                this["AsiTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Data.DataTable BPproductTable {
            get {
                return ((global::System.Data.DataTable)(this["BPproductTable"]));
            }
            set {
                this["BPproductTable"] = value;
            }
        }
    }
}
